import { NextRequest, NextResponse } from "next/server"
import { generateText } from "ai"
import { getApiSession } from "@/lib/api-auth"

export const runtime = "nodejs"

// Same gateway model family the brainstorm route uses.
const AI_CHECK_MODEL = "openai/gpt-5-nano"

export interface AiCheckResult {
  likelihood: "low" | "medium" | "high"
  summary: string
  observations: string[]
}

const SYSTEM = `You are a writing-integrity assistant for a high school. You review a student's essay draft and estimate how likely it is that substantial portions were generated by an AI tool rather than written by the student.

Consider signals like: uniformly polished sentence structure, generic hedged phrasing, absence of personal voice or concrete personal detail, formulaic five-paragraph transitions ("Furthermore", "In conclusion", "It is important to note"), unnaturally consistent register, and encyclopedic tone. Also consider counter-signals: typos, idiosyncratic phrasing, specific personal anecdotes, uneven quality.

Be honest that this is an estimate — AI detection from text alone is unreliable, and strong writers can sound "AI-like".

Respond with ONLY a JSON object, no markdown fence:
{"likelihood": "low" | "medium" | "high", "summary": "<one- or two-sentence overall read>", "observations": ["<specific observation>", ...]}

Give 3-6 observations, each tied to something concrete in the text.`

export async function POST(req: NextRequest) {
  const user = await getApiSession(req)
  if (!user) {
    return NextResponse.json({ error: "Not signed in" }, { status: 401 })
  }

  let body: { text?: string }
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 })
  }

  const text = (body.text ?? "").trim()
  if (text.split(/\s+/).length < 30) {
    return NextResponse.json(
      { error: "The essay is too short to analyze — keep writing first." },
      { status: 400 }
    )
  }

  try {
    const result = await generateText({
      model: AI_CHECK_MODEL,
      system: SYSTEM,
      prompt: `Student essay draft:\n\n${text.slice(0, 24_000)}`,
    })

    // The model is instructed to return bare JSON; strip a stray fence anyway.
    const raw = result.text.trim().replace(/^```(?:json)?\s*|\s*```$/g, "")
    const parsed = JSON.parse(raw) as AiCheckResult
    if (!["low", "medium", "high"].includes(parsed.likelihood)) {
      throw new Error("bad likelihood")
    }
    return NextResponse.json({
      likelihood: parsed.likelihood,
      summary: String(parsed.summary ?? ""),
      observations: Array.isArray(parsed.observations)
        ? parsed.observations.map(String).slice(0, 6)
        : [],
    })
  } catch {
    return NextResponse.json(
      { error: "The check could not be completed. Please try again." },
      { status: 502 }
    )
  }
}
