import type { FormPageConfig } from "@/lib/form-types"

const XANO_BASE =
  process.env.NEXT_PUBLIC_XANO_API_BASE ??
  "https://xsc3-mvx7-r86m.n7e.xano.io/api:o2_UyOKn"

export const housingConfig: FormPageConfig = {
  xanoEndpoint: `${XANO_BASE}/lifeplan_housing`,
  xanoLoadEndpoint: `${XANO_BASE}/lifeplan_housing_by_student_id`,
  defaultValues: {
    user_email: "",
    students_id: null,
    housing_image_1: null,
    housing_image_2: null,
    housing_type: "",
    location: "",
    room_configuration: "",
    roommate_situation: "",
    distance_to_work_school_or_program: "",
    reason_chosen: "",
    meets_needs_explanation: "",
    alternative_housing_considered: "",
    monthly_rent: 0,
    housing_deposit: 0,
    utilities_cost: 0,
    internet_cost: 0,
    move_in_date: "",
    term_commitment: "",
    housing_description: "",
    amenities_included: "",
    housing_policies_rules: "",
  },
  sections: [
    {
      title: "Your Housing Choice",
      fields: [
        "housing_image_1",
        "housing_image_2",
        "housing_type",
        "location",
        "room_configuration",
      ],
    },
    {
      title: "Living Situation",
      fields: [
        "roommate_situation",
        "distance_to_work_school_or_program",
        "reason_chosen",
        "meets_needs_explanation",
        "alternative_housing_considered",
      ],
    },
    {
      title: "Costs",
      fields: ["monthly_rent", "housing_deposit", "utilities_cost", "internet_cost"],
    },
    {
      title: "Details",
      fields: [
        "move_in_date",
        "term_commitment",
        "housing_description",
        "amenities_included",
        "housing_policies_rules",
      ],
    },
  ],
  fields: [
    { name: "user_email", type: "hidden", section: "" },
    { name: "students_id", type: "hidden", section: "" },
    { name: "housing_image_1", type: "image", label: "Housing Image 1", required: true, section: "Your Housing Choice", columns: 2 },
    { name: "housing_image_2", type: "image", label: "Housing Image 2", required: true, section: "Your Housing Choice", columns: 2 },
    { name: "housing_type", type: "select", label: "Housing Type", placeholder: "Select housing type...", options: ["Apartment", "House", "Room Rental", "Dorm", "Other"], required: true, section: "Your Housing Choice" },
    { name: "location", type: "text", label: "Location", placeholder: "Address or area description", required: true, section: "Your Housing Choice" },
    { name: "room_configuration", type: "select", label: "Room Configuration", placeholder: "Select configuration...", options: ["Studio", "1BR", "2BR", "3BR+", "Shared Room"], required: true, section: "Your Housing Choice" },
    { name: "roommate_situation", type: "text", label: "Roommate Situation", required: true, section: "Living Situation" },
    { name: "distance_to_work_school_or_program", type: "text", label: "Distance to Work / School / Program", required: true, section: "Living Situation" },
    { name: "reason_chosen", type: "textarea", label: "Why did you choose this housing?", minWords: 50, required: true, section: "Living Situation" },
    { name: "meets_needs_explanation", type: "textarea", label: "How does it meet your needs?", minWords: 50, required: true, section: "Living Situation" },
    { name: "alternative_housing_considered", type: "textarea", label: "What alternatives did you consider?", minWords: 30, required: true, section: "Living Situation" },
    { name: "monthly_rent", type: "number", label: "Monthly Rent", required: true, section: "Costs" },
    { name: "housing_deposit", type: "number", label: "Housing Deposit", required: true, section: "Costs" },
    { name: "utilities_cost", type: "number", label: "Utilities Cost", required: true, section: "Costs" },
    { name: "internet_cost", type: "number", label: "Internet Cost", required: true, section: "Costs" },
    { name: "move_in_date", type: "date", label: "Move-in Date", required: true, section: "Details" },
    { name: "term_commitment", type: "select", label: "Term Commitment", placeholder: "Select term...", options: ["Month-to-month", "6 months", "12 months", "Other"], required: true, section: "Details" },
    { name: "housing_description", type: "textarea", label: "Describe the place", minWords: 75, required: true, section: "Details" },
    { name: "amenities_included", type: "textarea", label: "Amenities Included", minWords: 30, required: true, section: "Details" },
    { name: "housing_policies_rules", type: "textarea", label: "Housing Policies & Rules", minWords: 30, required: true, section: "Details" },
  ],
}

export const educationConfig: FormPageConfig = {
  xanoEndpoint: `${XANO_BASE}/lifeplan_education`,
  xanoLoadEndpoint: `${XANO_BASE}/lifeplan_education_by_student_id`,
  defaultValues: {
    user_email: "",
    students_id: null,
    school_photo: null,
    school_logo: null,
    institution_program_name: "",
    program_type: "",
    field_of_study_specialty: "",
    program_length: "",
    completion_requirements: "",
    credentials_upon_completion: "",
    school_program_website: "",
    why_you_chose_this_program: "",
    how_it_meets_career_goals: "",
    program_differentiators: "",
    campus_program_photo: null,
    program_photo_2: null,
    program_photo_3: null,
    location_photo: null,
    city_and_state: "",
    distance_from_home: "",
    transportation_requirements: "",
    climate_environment: "",
    program_key_features_campus_life_amenities: "",
    special_opportunities: "",
    application_open_date: "",
    application_deadline_date: "",
    prerequisites: "",
    testing_minimum_requirements: "",
    other_application_requirements: "",
    college_admission_exam_name_1: "",
    college_admission_exam_scores_1: "",
    college_admission_exam_name_2: "",
    college_admission_exam_scores_2: "",
    high_school_gpa: "",
    high_school_transcript_url_link: "",
    total_annual_program_cost: 0,
    tuition: 0,
    room_and_board: 0,
    books_equipment_tools_expenses: 0,
    additional_fees: 0,
    total_annual_cost: 0,
    financial_assistance_total_estimated: 0,
    merit_scholarship_total: 0,
    need_based_grant_total: 0,
    federal_loan_total: 0,
    financial_assistance_information: "",
    remaining_annual_cost: 0,
    plan_to_cover_remaining_costs: "",
  },
  sections: [
    {
      title: "Program Overview",
      fields: [
        "school_photo",
        "school_logo",
        "institution_program_name",
        "program_type",
        "field_of_study_specialty",
        "program_length",
        "credentials_upon_completion",
        "school_program_website",
      ],
    },
    {
      title: "Program Details",
      fields: [
        "completion_requirements",
        "why_you_chose_this_program",
        "how_it_meets_career_goals",
        "program_differentiators",
      ],
    },
    {
      title: "Campus & Location",
      fields: [
        "campus_program_photo",
        "location_photo",
        "program_photo_2",
        "program_photo_3",
        "city_and_state",
        "distance_from_home",
        "transportation_requirements",
        "climate_environment",
        "program_key_features_campus_life_amenities",
        "special_opportunities",
      ],
    },
    {
      title: "Application Requirements",
      fields: [
        "application_open_date",
        "application_deadline_date",
        "prerequisites",
        "testing_minimum_requirements",
        "other_application_requirements",
        "college_admission_exam_name_1",
        "college_admission_exam_scores_1",
        "college_admission_exam_name_2",
        "college_admission_exam_scores_2",
        "high_school_gpa",
        "high_school_transcript_url_link",
      ],
    },
    {
      title: "Costs",
      fields: [
        "total_annual_program_cost",
        "tuition",
        "room_and_board",
        "books_equipment_tools_expenses",
        "additional_fees",
        "total_annual_cost",
      ],
    },
    {
      title: "Financial Assistance",
      fields: [
        "financial_assistance_total_estimated",
        "merit_scholarship_total",
        "need_based_grant_total",
        "federal_loan_total",
        "financial_assistance_information",
        "remaining_annual_cost",
        "plan_to_cover_remaining_costs",
      ],
    },
  ],
  fields: [
    { name: "user_email", type: "hidden", section: "" },
    { name: "students_id", type: "hidden", section: "" },

    // Program Overview
    { name: "school_photo", type: "image", label: "School Photo", section: "Program Overview", columns: 2 },
    { name: "school_logo", type: "image", label: "School Logo", section: "Program Overview", columns: 2 },
    { name: "institution_program_name", type: "text", label: "Institution / Program Name", placeholder: "e.g. University of South Florida", required: true, section: "Program Overview" },
    { name: "program_type", type: "select", label: "Program Type", placeholder: "Select program type...", options: ["4-Year University", "2-Year College", "Trade / Vocational", "Certificate Program", "Apprenticeship", "Military", "Other"], required: true, section: "Program Overview" },
    { name: "field_of_study_specialty", type: "text", label: "Field of Study / Specialty", placeholder: "e.g. Marine Biology, Welding, Business", required: true, section: "Program Overview" },
    { name: "program_length", type: "text", label: "Program Length", placeholder: "e.g. 4 years, 18 months", required: true, section: "Program Overview" },
    { name: "credentials_upon_completion", type: "text", label: "Credentials Upon Completion", placeholder: "e.g. Bachelor's Degree, ASE Certification", required: true, section: "Program Overview" },
    { name: "school_program_website", type: "text", label: "School / Program Website", placeholder: "https://...", section: "Program Overview" },

    // Program Details
    { name: "completion_requirements", type: "textarea", label: "Completion Requirements", placeholder: "What do you need to complete to finish this program?", minWords: 30, required: true, section: "Program Details" },
    { name: "why_you_chose_this_program", type: "textarea", label: "Why You Chose This Program", placeholder: "Explain why this program is the right fit for you.", minWords: 75, required: true, section: "Program Details" },
    { name: "how_it_meets_career_goals", type: "textarea", label: "How It Meets Your Career Goals", placeholder: "How will this program help you achieve your career goals?", minWords: 75, required: true, section: "Program Details" },
    { name: "program_differentiators", type: "textarea", label: "What Makes This Program Stand Out?", placeholder: "What sets this program apart from other options?", minWords: 50, required: true, section: "Program Details" },

    // Campus & Location
    { name: "campus_program_photo", type: "image", label: "Campus / Program Photo", section: "Campus & Location", columns: 2 },
    { name: "location_photo", type: "image", label: "Location Photo", section: "Campus & Location", columns: 2 },
    { name: "program_photo_2", type: "image", label: "Program Photo 2", section: "Campus & Location", columns: 2 },
    { name: "program_photo_3", type: "image", label: "Program Photo 3", section: "Campus & Location", columns: 2 },
    { name: "city_and_state", type: "text", label: "City & State", placeholder: "e.g. Tampa, FL", required: true, section: "Campus & Location" },
    { name: "distance_from_home", type: "text", label: "Distance from Home", placeholder: "e.g. 30 minutes, 3 hours", required: true, section: "Campus & Location" },
    { name: "transportation_requirements", type: "text", label: "Transportation Requirements", placeholder: "e.g. Car needed, bus route available", section: "Campus & Location" },
    { name: "climate_environment", type: "text", label: "Climate & Environment", placeholder: "e.g. Subtropical, urban campus", section: "Campus & Location" },
    { name: "program_key_features_campus_life_amenities", type: "textarea", label: "Key Features, Campus Life & Amenities", placeholder: "Describe what the campus and program life are like.", minWords: 50, section: "Campus & Location" },
    { name: "special_opportunities", type: "textarea", label: "Special Opportunities", placeholder: "e.g. Internships, study abroad, co-ops, research", minWords: 30, section: "Campus & Location" },

    // Application Requirements
    { name: "application_open_date", type: "date", label: "Application Open Date", section: "Application Requirements" },
    { name: "application_deadline_date", type: "date", label: "Application Deadline", required: true, section: "Application Requirements" },
    { name: "prerequisites", type: "textarea", label: "Prerequisites", placeholder: "What prerequisites are required for admission?", minWords: 20, section: "Application Requirements" },
    { name: "testing_minimum_requirements", type: "textarea", label: "Testing / Minimum Requirements", placeholder: "e.g. SAT scores, placement tests", minWords: 20, section: "Application Requirements" },
    { name: "other_application_requirements", type: "textarea", label: "Other Application Requirements", placeholder: "e.g. Essays, letters of recommendation, portfolio", minWords: 20, section: "Application Requirements" },
    { name: "college_admission_exam_name_1", type: "text", label: "Admission Exam 1 — Name", placeholder: "e.g. SAT, ACT, ASVAB", section: "Application Requirements" },
    { name: "college_admission_exam_scores_1", type: "text", label: "Admission Exam 1 — Score", placeholder: "Your score or target score", section: "Application Requirements" },
    { name: "college_admission_exam_name_2", type: "text", label: "Admission Exam 2 — Name", placeholder: "e.g. SAT Subject Test", section: "Application Requirements" },
    { name: "college_admission_exam_scores_2", type: "text", label: "Admission Exam 2 — Score", placeholder: "Your score or target score", section: "Application Requirements" },
    { name: "high_school_gpa", type: "text", label: "High School GPA", placeholder: "e.g. 3.2", section: "Application Requirements" },
    { name: "high_school_transcript_url_link", type: "text", label: "High School Transcript URL", placeholder: "https://...", section: "Application Requirements" },

    // Costs
    { name: "total_annual_program_cost", type: "number", label: "Total Annual Program Cost", required: true, section: "Costs" },
    { name: "tuition", type: "number", label: "Tuition", required: true, section: "Costs" },
    { name: "room_and_board", type: "number", label: "Room & Board", section: "Costs" },
    { name: "books_equipment_tools_expenses", type: "number", label: "Books, Equipment & Tools", section: "Costs" },
    { name: "additional_fees", type: "number", label: "Additional Fees", section: "Costs" },
    { name: "total_annual_cost", type: "number", label: "Total Annual Cost", required: true, section: "Costs" },

    // Financial Assistance
    { name: "financial_assistance_total_estimated", type: "number", label: "Financial Assistance — Total Estimated", section: "Financial Assistance" },
    { name: "merit_scholarship_total", type: "number", label: "Merit Scholarship Total", section: "Financial Assistance" },
    { name: "need_based_grant_total", type: "number", label: "Need-Based Grant Total", section: "Financial Assistance" },
    { name: "federal_loan_total", type: "number", label: "Federal Loan Total", section: "Financial Assistance" },
    { name: "financial_assistance_information", type: "textarea", label: "Financial Assistance Information", placeholder: "Describe any scholarships, grants, or aid you've applied for or received.", minWords: 30, section: "Financial Assistance" },
    { name: "remaining_annual_cost", type: "number", label: "Remaining Annual Cost", section: "Financial Assistance" },
    { name: "plan_to_cover_remaining_costs", type: "textarea", label: "Plan to Cover Remaining Costs", placeholder: "How will you cover costs not covered by aid?", minWords: 50, required: true, section: "Financial Assistance" },
  ],
}

export const personalProfileConfig: FormPageConfig = {
  xanoEndpoint: `${XANO_BASE}/lifeplan_personalprofile`,
  xanoLoadEndpoint: `${XANO_BASE}/lifeplan_personalprofile_by_studentid`,
  defaultValues: {
    user_email: "",
    students_id: null,
    fillout_id: "",
    personality_results: "",
    personality_name: "",
    personality_summary: "",
    personality_trait_1: "",
    personality_trait_2: "",
    personality_trait_3: "",
    personality_trait_4: "",
    personality_trait_5: "",
    additional_trait_1: "",
    additional_trait_2: "",
    additional_trait_3: "",
    core_value_1: "",
    core_value_2: "",
    core_value_3: "",
    core_value_4: "",
    strength_1: "",
    strength_2: "",
    strength_3: "",
    strength_4: "",
    strength_5: "",
    growth_area_1: "",
    growth_area_2: "",
    hard_skill_1: "",
    hard_skill_2: "",
    hard_skill_3: "",
    hard_skill_4: "",
    hard_skill_5: "",
    soft_skill_1: "",
    soft_skill_2: "",
    soft_skill_3: "",
    soft_skill_4: "",
    soft_skill_5: "",
    hobbies: "",
    hobby_1: "",
    hobby_2: "",
    hobby_3: "",
    hobby_4: "",
    hobby_5: "",
    topic_1: "",
    topic_2: "",
    topic_3: "",
    topic_4: "",
    short_goal_1: "",
    short_goal_2: "",
    med_goal_1: "",
    med_goal_2: "",
    long_goal: "",
  },
  sections: [
    {
      title: "Personality Profile",
      fields: [
        "personality_results",
        "personality_name",
        "personality_summary",
        "personality_trait_1",
        "personality_trait_2",
        "personality_trait_3",
        "personality_trait_4",
        "personality_trait_5",
        "additional_trait_1",
        "additional_trait_2",
        "additional_trait_3",
      ],
    },
    {
      title: "Core Values & Strengths",
      fields: [
        "core_value_1",
        "core_value_2",
        "core_value_3",
        "core_value_4",
        "strength_1",
        "strength_2",
        "strength_3",
        "strength_4",
        "strength_5",
        "growth_area_1",
        "growth_area_2",
      ],
    },
    {
      title: "Skills",
      fields: [
        "hard_skill_1",
        "hard_skill_2",
        "hard_skill_3",
        "hard_skill_4",
        "hard_skill_5",
        "soft_skill_1",
        "soft_skill_2",
        "soft_skill_3",
        "soft_skill_4",
        "soft_skill_5",
      ],
    },
    {
      title: "Hobbies & Interests",
      fields: [
        "hobbies",
        "hobby_1",
        "hobby_2",
        "hobby_3",
        "hobby_4",
        "hobby_5",
        "topic_1",
        "topic_2",
        "topic_3",
        "topic_4",
      ],
    },
    {
      title: "Goals",
      fields: [
        "short_goal_1",
        "short_goal_2",
        "med_goal_1",
        "med_goal_2",
        "long_goal",
      ],
    },
  ],
  fields: [
    { name: "user_email", type: "hidden", section: "" },
    { name: "students_id", type: "hidden", section: "" },
    { name: "fillout_id", type: "hidden", section: "" },

    // Personality Profile
    { name: "personality_results", type: "select", label: "Personality Type", placeholder: "Select your type...", options: ["INTJ", "INTP", "ENTJ", "ENTP", "INFJ", "INFP", "ENFJ", "ENFP", "ISTJ", "ISFJ", "ESTJ", "ESFJ", "ISTP", "ISFP", "ESTP", "ESFP"], section: "Personality Profile" },
    { name: "personality_name", type: "text", label: "Personality Assessment Name", placeholder: "e.g. Myers-Briggs, 16Personalities", section: "Personality Profile" },
    { name: "personality_summary", type: "textarea", label: "Personality Analysis", placeholder: "Describe your personality type and what it means to you.", minWords: 50, required: true, section: "Personality Profile" },
    { name: "personality_trait_1", type: "text", label: "Personality Trait #1", placeholder: "e.g. Analytical, Creative, Empathetic", required: true, section: "Personality Profile", columns: 3 },
    { name: "personality_trait_2", type: "text", label: "Personality Trait #2", section: "Personality Profile", columns: 3 },
    { name: "personality_trait_3", type: "text", label: "Personality Trait #3", section: "Personality Profile", columns: 3 },
    { name: "personality_trait_4", type: "text", label: "Personality Trait #4", section: "Personality Profile", columns: 3 },
    { name: "personality_trait_5", type: "text", label: "Personality Trait #5", section: "Personality Profile", columns: 3 },
    { name: "additional_trait_1", type: "text", label: "Additional Trait #1", section: "Personality Profile", columns: 3 },
    { name: "additional_trait_2", type: "text", label: "Additional Trait #2", section: "Personality Profile", columns: 3 },
    { name: "additional_trait_3", type: "text", label: "Additional Trait #3", section: "Personality Profile", columns: 3 },

    // Core Values & Strengths
    { name: "core_value_1", type: "text", label: "Core Value #1", placeholder: "e.g. Integrity, Family, Growth", required: true, section: "Core Values & Strengths", columns: 3 },
    { name: "core_value_2", type: "text", label: "Core Value #2", required: true, section: "Core Values & Strengths", columns: 3 },
    { name: "core_value_3", type: "text", label: "Core Value #3", section: "Core Values & Strengths", columns: 3 },
    { name: "core_value_4", type: "text", label: "Core Value #4", section: "Core Values & Strengths", columns: 3 },
    { name: "strength_1", type: "text", label: "Personal Strength #1", placeholder: "e.g. Leadership, Problem-solving", required: true, section: "Core Values & Strengths", columns: 3 },
    { name: "strength_2", type: "text", label: "Personal Strength #2", required: true, section: "Core Values & Strengths", columns: 3 },
    { name: "strength_3", type: "text", label: "Personal Strength #3", section: "Core Values & Strengths", columns: 3 },
    { name: "strength_4", type: "text", label: "Personal Strength #4", section: "Core Values & Strengths", columns: 3 },
    { name: "strength_5", type: "text", label: "Personal Strength #5", section: "Core Values & Strengths", columns: 3 },
    { name: "growth_area_1", type: "text", label: "Area for Growth #1", placeholder: "e.g. Public speaking, Time management", required: true, section: "Core Values & Strengths", columns: 3 },
    { name: "growth_area_2", type: "text", label: "Area for Growth #2", section: "Core Values & Strengths", columns: 3 },

    // Skills
    { name: "hard_skill_1", type: "text", label: "Hard Skill #1", placeholder: "e.g. Welding, Coding, Accounting", required: true, section: "Skills", columns: 3 },
    { name: "hard_skill_2", type: "text", label: "Hard Skill #2", section: "Skills", columns: 3 },
    { name: "hard_skill_3", type: "text", label: "Hard Skill #3", section: "Skills", columns: 3 },
    { name: "hard_skill_4", type: "text", label: "Hard Skill #4", section: "Skills", columns: 3 },
    { name: "hard_skill_5", type: "text", label: "Hard Skill #5", section: "Skills", columns: 3 },
    { name: "soft_skill_1", type: "text", label: "Soft Skill #1", placeholder: "e.g. Communication, Teamwork, Adaptability", required: true, section: "Skills", columns: 3 },
    { name: "soft_skill_2", type: "text", label: "Soft Skill #2", section: "Skills", columns: 3 },
    { name: "soft_skill_3", type: "text", label: "Soft Skill #3", section: "Skills", columns: 3 },
    { name: "soft_skill_4", type: "text", label: "Soft Skill #4", section: "Skills", columns: 3 },
    { name: "soft_skill_5", type: "text", label: "Soft Skill #5", section: "Skills", columns: 3 },

    // Hobbies & Interests
    { name: "hobbies", type: "textarea", label: "Hobbies & Interests Overview", placeholder: "Describe your hobbies and interests.", minWords: 30, section: "Hobbies & Interests" },
    { name: "hobby_1", type: "text", label: "Hobby #1", placeholder: "e.g. Fishing, Drawing, Basketball", required: true, section: "Hobbies & Interests", columns: 3 },
    { name: "hobby_2", type: "text", label: "Hobby #2", section: "Hobbies & Interests", columns: 3 },
    { name: "hobby_3", type: "text", label: "Hobby #3", section: "Hobbies & Interests", columns: 3 },
    { name: "hobby_4", type: "text", label: "Hobby #4", section: "Hobbies & Interests", columns: 3 },
    { name: "hobby_5", type: "text", label: "Hobby #5", section: "Hobbies & Interests", columns: 3 },
    { name: "topic_1", type: "text", label: "Subject / Topic You Enjoy #1", placeholder: "e.g. Marine Science, History, Music", required: true, section: "Hobbies & Interests", columns: 3 },
    { name: "topic_2", type: "text", label: "Subject / Topic You Enjoy #2", section: "Hobbies & Interests", columns: 3 },
    { name: "topic_3", type: "text", label: "Subject / Topic You Enjoy #3", section: "Hobbies & Interests", columns: 3 },
    { name: "topic_4", type: "text", label: "Subject / Topic You Enjoy #4", section: "Hobbies & Interests", columns: 3 },

    // Goals
    { name: "short_goal_1", type: "text", label: "Short-Term Goal #1 (1–2 years)", placeholder: "What do you want to achieve in the next 1–2 years?", required: true, section: "Goals", columns: 3 },
    { name: "short_goal_2", type: "text", label: "Short-Term Goal #2 (1–2 years)", section: "Goals", columns: 3 },
    { name: "med_goal_1", type: "text", label: "Medium-Term Goal #1 (2–5 years)", placeholder: "Where do you see yourself in 2–5 years?", required: true, section: "Goals", columns: 3 },
    { name: "med_goal_2", type: "text", label: "Medium-Term Goal #2 (2–5 years)", section: "Goals", columns: 3 },
    { name: "long_goal", type: "textarea", label: "Long-Term Goal (5+ years)", placeholder: "Describe your long-term vision for your life.", minWords: 50, required: true, section: "Goals" },
  ],
}

export const transportationConfig: FormPageConfig = {
  xanoEndpoint: `${XANO_BASE}/lifeplan_transportation`,
  xanoLoadEndpoint: `${XANO_BASE}/lifeplan_transportation_by_studentid`,
  defaultValues: {
    user_email: "",
    students_id: null,
    fillout_id: "",
    primary_transportation_method: "",
    transportation_method_description: "",
    distance_to_program_or_work: "",
    commute_time_estimated: "",
    transportation_method_reason: "",
    license_type: "",
    license_expiration_date: "",
    license_status: "",
    vehicle_purchase_plan: "",
    vehicle_image: null,
    vehicle_make_model: "",
    vehicle_year: "",
    vehicle_mileage: "",
    vehicle_condition: "",
    car_financing_method: "",
    vehicle_price: 0,
    down_payment_percentage: "",
    down_payment_amount: 0,
    loan_term: "",
    loan_amount: 0,
    interest_rate_percent: "",
    monthly_payment: 0,
    down_payment_savings_plan: "",
    maintenance_budget: 0,
    insurance_monthly_payment: 0,
    estimated_gas_cost: 0,
    registration_fees: 0,
    total_monthly_vehicle_cost: 0,
    initial_down_payment: 0,
    tax_title_license_cost: 0,
    initial_insurance_payment: 0,
    total_one_time_vehicle_costs: 0,
    vehicle_choice_reason: "",
    vehicle_meets_needs: "",
    alternative_vehicles_considered: "",
    vehicle_purchase_savings_plan: "",
    insurance_logo: null,
    current_coverage: "",
    insurance_provider: "",
    coverage_type: "",
    monthly_premium: 0,
    insurance_status: "",
  },
  sections: [
    {
      title: "Transportation Method",
      fields: [
        "primary_transportation_method",
        "transportation_method_description",
        "distance_to_program_or_work",
        "commute_time_estimated",
        "transportation_method_reason",
      ],
    },
    {
      title: "License & Readiness",
      fields: [
        "license_type",
        "license_status",
        "license_expiration_date",
        "vehicle_purchase_plan",
      ],
    },
    {
      title: "Vehicle Details",
      fields: [
        "vehicle_image",
        "vehicle_make_model",
        "vehicle_year",
        "vehicle_mileage",
        "vehicle_condition",
      ],
    },
    {
      title: "Vehicle Financing",
      fields: [
        "car_financing_method",
        "vehicle_price",
        "down_payment_percentage",
        "down_payment_amount",
        "loan_term",
        "loan_amount",
        "interest_rate_percent",
        "monthly_payment",
        "down_payment_savings_plan",
      ],
    },
    {
      title: "Monthly Vehicle Costs",
      fields: [
        "maintenance_budget",
        "insurance_monthly_payment",
        "estimated_gas_cost",
        "registration_fees",
        "total_monthly_vehicle_cost",
      ],
    },
    {
      title: "One-Time Vehicle Costs",
      fields: [
        "initial_down_payment",
        "tax_title_license_cost",
        "initial_insurance_payment",
        "total_one_time_vehicle_costs",
      ],
    },
    {
      title: "Vehicle Choice Reasoning",
      fields: [
        "vehicle_choice_reason",
        "vehicle_meets_needs",
        "alternative_vehicles_considered",
        "vehicle_purchase_savings_plan",
      ],
    },
    {
      title: "Insurance",
      fields: [
        "insurance_logo",
        "insurance_provider",
        "coverage_type",
        "current_coverage",
        "monthly_premium",
        "insurance_status",
      ],
    },
  ],
  fields: [
    { name: "user_email", type: "hidden", section: "" },
    { name: "students_id", type: "hidden", section: "" },
    { name: "fillout_id", type: "hidden", section: "" },

    // Transportation Method
    { name: "primary_transportation_method", type: "select", label: "Primary Transportation Method", placeholder: "Select method...", options: ["Personal Vehicle", "Public Transit", "Bicycle", "Walking", "Rideshare", "Carpool", "Other"], required: true, section: "Transportation Method" },
    { name: "transportation_method_description", type: "textarea", label: "Describe Your Transportation Plan", placeholder: "How will you get to work, school, and other destinations?", minWords: 50, required: true, section: "Transportation Method" },
    { name: "distance_to_program_or_work", type: "text", label: "Distance to Program / Work", placeholder: "e.g. 12 miles, 30 minutes", required: true, section: "Transportation Method" },
    { name: "commute_time_estimated", type: "text", label: "Estimated Commute Time", placeholder: "e.g. 25 minutes each way", required: true, section: "Transportation Method" },
    { name: "transportation_method_reason", type: "textarea", label: "Why Did You Choose This Method?", placeholder: "Explain why this transportation option is the best fit for you.", minWords: 30, required: true, section: "Transportation Method" },

    // License & Readiness
    { name: "license_type", type: "select", label: "License Type", placeholder: "Select type...", options: ["Learner's Permit", "Driver's License", "Motorcycle License", "Commercial License (CDL)", "None"], section: "License & Readiness" },
    { name: "license_status", type: "select", label: "License Status", placeholder: "Select status...", options: ["Active", "Expired", "Suspended", "Not Yet Obtained", "In Progress"], section: "License & Readiness" },
    { name: "license_expiration_date", type: "date", label: "License Expiration Date", section: "License & Readiness" },
    { name: "vehicle_purchase_plan", type: "textarea", label: "Vehicle Purchase Plan", placeholder: "Describe your plan and timeline for purchasing a vehicle.", minWords: 30, section: "License & Readiness" },

    // Vehicle Details
    { name: "vehicle_image", type: "image", label: "Vehicle Photo", section: "Vehicle Details" },
    { name: "vehicle_make_model", type: "text", label: "Make & Model", placeholder: "e.g. 2018 Honda Civic", section: "Vehicle Details" },
    { name: "vehicle_year", type: "text", label: "Year", placeholder: "e.g. 2018", section: "Vehicle Details" },
    { name: "vehicle_mileage", type: "text", label: "Mileage", placeholder: "e.g. 45,000 miles", section: "Vehicle Details" },
    { name: "vehicle_condition", type: "select", label: "Condition", placeholder: "Select condition...", options: ["New", "Like New", "Good", "Fair", "Needs Work"], section: "Vehicle Details" },

    // Vehicle Financing
    { name: "car_financing_method", type: "select", label: "Financing Method", placeholder: "Select method...", options: ["Cash / Savings", "Auto Loan", "Lease", "Family Gift", "Other"], section: "Vehicle Financing" },
    { name: "vehicle_price", type: "number", label: "Vehicle Price", required: true, section: "Vehicle Financing" },
    { name: "down_payment_percentage", type: "text", label: "Down Payment %", placeholder: "e.g. 20%", section: "Vehicle Financing" },
    { name: "down_payment_amount", type: "number", label: "Down Payment Amount", section: "Vehicle Financing" },
    { name: "loan_term", type: "select", label: "Loan Term", placeholder: "Select term...", options: ["24 months", "36 months", "48 months", "60 months", "72 months"], section: "Vehicle Financing" },
    { name: "loan_amount", type: "number", label: "Loan Amount", section: "Vehicle Financing" },
    { name: "interest_rate_percent", type: "text", label: "Interest Rate %", placeholder: "e.g. 5.9%", section: "Vehicle Financing" },
    { name: "monthly_payment", type: "number", label: "Monthly Payment", section: "Vehicle Financing" },
    { name: "down_payment_savings_plan", type: "textarea", label: "Down Payment Savings Plan", placeholder: "How are you saving for the down payment?", minWords: 30, section: "Vehicle Financing" },

    // Monthly Vehicle Costs
    { name: "maintenance_budget", type: "number", label: "Maintenance Budget", section: "Monthly Vehicle Costs" },
    { name: "insurance_monthly_payment", type: "number", label: "Insurance (Monthly)", section: "Monthly Vehicle Costs" },
    { name: "estimated_gas_cost", type: "number", label: "Estimated Gas Cost", section: "Monthly Vehicle Costs" },
    { name: "registration_fees", type: "number", label: "Registration Fees", section: "Monthly Vehicle Costs" },
    { name: "total_monthly_vehicle_cost", type: "number", label: "Total Monthly Vehicle Cost", section: "Monthly Vehicle Costs" },

    // One-Time Vehicle Costs
    { name: "initial_down_payment", type: "number", label: "Initial Down Payment", section: "One-Time Vehicle Costs" },
    { name: "tax_title_license_cost", type: "number", label: "Tax, Title & License", section: "One-Time Vehicle Costs" },
    { name: "initial_insurance_payment", type: "number", label: "Initial Insurance Payment", section: "One-Time Vehicle Costs" },
    { name: "total_one_time_vehicle_costs", type: "number", label: "Total One-Time Costs", section: "One-Time Vehicle Costs" },

    // Vehicle Choice Reasoning
    { name: "vehicle_choice_reason", type: "textarea", label: "Why Did You Choose This Vehicle?", placeholder: "Explain why this vehicle is the right fit for you.", minWords: 50, required: true, section: "Vehicle Choice Reasoning" },
    { name: "vehicle_meets_needs", type: "textarea", label: "How Does It Meet Your Needs?", placeholder: "How does this vehicle support your daily life and goals?", minWords: 50, required: true, section: "Vehicle Choice Reasoning" },
    { name: "alternative_vehicles_considered", type: "textarea", label: "Alternative Vehicles Considered", placeholder: "What other vehicles did you research or consider?", minWords: 30, section: "Vehicle Choice Reasoning" },
    { name: "vehicle_purchase_savings_plan", type: "textarea", label: "Vehicle Purchase Savings Plan", placeholder: "Describe your savings strategy for purchasing this vehicle.", minWords: 30, section: "Vehicle Choice Reasoning" },

    // Insurance
    { name: "insurance_logo", type: "image", label: "Insurance Provider Logo", section: "Insurance" },
    { name: "insurance_provider", type: "text", label: "Insurance Provider", placeholder: "e.g. GEICO, State Farm, Progressive", required: true, section: "Insurance" },
    { name: "coverage_type", type: "select", label: "Coverage Type", placeholder: "Select coverage...", options: ["Liability Only", "Collision", "Comprehensive", "Full Coverage", "Other"], section: "Insurance" },
    { name: "current_coverage", type: "textarea", label: "Current Coverage Details", placeholder: "Describe your current insurance coverage.", minWords: 20, section: "Insurance" },
    { name: "monthly_premium", type: "number", label: "Monthly Premium", section: "Insurance" },
    { name: "insurance_status", type: "select", label: "Insurance Status", placeholder: "Select status...", options: ["Active", "Pending", "Not Yet Obtained", "Lapsed"], section: "Insurance" },
  ],
}

export const pathwayConfig: FormPageConfig = {
  xanoEndpoint: `${XANO_BASE}/lifeplan_pathway`,
  defaultValues: {
    user_email: "",
    students_id: null,
    fillout_id: "",
    pathway_image_1: null,
    pathway_image_2: null,
    pathway: "",
    field_of_study: "",
    why: "",
    other_pathways: "",
  },
  sections: [
    {
      title: "Your Selected Pathway",
      fields: [
        "pathway",
        "field_of_study",
        "pathway_image_1",
        "pathway_image_2",
      ],
    },
    {
      title: "Pathway Reasoning",
      fields: [
        "why",
        "other_pathways",
      ],
    },
  ],
  fields: [
    { name: "user_email", type: "hidden", section: "" },
    { name: "students_id", type: "hidden", section: "" },
    { name: "fillout_id", type: "hidden", section: "" },

    // Your Selected Pathway
    { name: "pathway", type: "select", label: "Pathway", placeholder: "Select your pathway...", options: ["Post-Secondary Education", "Trade School", "Apprenticeship", "Military", "Entrepreneurship", "Workforce", "Other"], required: true, section: "Your Selected Pathway" },
    { name: "field_of_study", type: "text", label: "Field of Study / Specialty", placeholder: "e.g. Electrician, Nursing, Business", required: true, section: "Your Selected Pathway" },
    { name: "pathway_image_1", type: "image", label: "Pathway Image 1", section: "Your Selected Pathway", columns: 2 },
    { name: "pathway_image_2", type: "image", label: "Pathway Image 2", section: "Your Selected Pathway", columns: 2 },

    // Pathway Reasoning
    { name: "why", type: "textarea", label: "Why Did You Choose This Pathway?", placeholder: "Explain why this pathway is the right fit for you, your goals, and your future.", minWords: 100, required: true, section: "Pathway Reasoning" },
    { name: "other_pathways", type: "textarea", label: "Other Pathways Considered", placeholder: "What other pathways did you consider and why did you ultimately choose a different direction?", minWords: 75, required: true, section: "Pathway Reasoning" },
  ],
}

export const sectionConfigMap: Record<string, { title: string; config: FormPageConfig; commentsEndpoint?: string }> = {
  housing: {
    title: "Housing & Living",
    config: housingConfig,
    commentsEndpoint: `${XANO_BASE}/lifemap_comments`,
  },
  education: {
    title: "Education",
    config: educationConfig,
    commentsEndpoint: `${XANO_BASE}/lifemap_comments`,
  },
  profile: {
    title: "Personal Profile",
    config: personalProfileConfig,
    commentsEndpoint: `${XANO_BASE}/lifemap_comments`,
  },
  transportation: {
    title: "Transportation",
    config: transportationConfig,
    commentsEndpoint: `${XANO_BASE}/lifemap_comments`,
  },
  pathway: {
    title: "Selected Pathway",
    config: pathwayConfig,
    commentsEndpoint: `${XANO_BASE}/lifemap_comments`,
  },
}
